baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Coffee Shop'
theme = 'coffee-ye'
copyright = 'All rights reserved'


# If false, English tags like `Getting Started` will be converted to `getting-started
preserveTaxonomyNames = true
# Automatically detects if Chinese/Japanese/Korean is included, this parameter affects the summary and word count functions and is recommended to be set to true
hasCJKLanguage = false
enableGitInfo = true

# Pagination
paginate = 10
paginatePath = "page"

# enable Emoji; see emoji-cheat-sheet.com
enableEmoji = false

disqus_shortname = "https-amber916young-github-io"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[mediaTypes]
  [mediaTypes."text/html"]
    suffixes = ["htm", "html"]

  [mediaTypes."application/javascript"]
    suffixes = ["js"]

    
[permalinks]
  post = "/:year/:month/:title/"

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]
  
[params.shareButtons]
  networks = [ "email", "linkedin", "reddit"]
  size = "small"
  buttonMargin = "0.2em"
  icon = "solid"

[params]
    keywords = "blog,life,code,desgin,yejiaYang,woman stem"
  author = "tothemoon"
  homepage = "Authentic Fresh Coffee"
  email = "youngyejia@163.com"
  avatar = "https://i.328888.xyz/2023/03/19/Pf8MH.png"
  description = "Design by yejiaYang. "
  aboutImage = "https://i.328888.xyz/2023/03/19/Pf8MH.png"
  [[params.social]]
      url   = "https://leetcode.com/BirdyYang/"
      icon  = "fa-brands fa-weibo  fa-lg" 

  [[params.social]]
      url   = "https://www.linkedin.com/in/yejia-yang-11105722a/"
      icon  = "fa-brands fa-linkedin fa-lg"
  [[params.social]]
      url = "https://www.instagram.com/tothemoonbird/"  
      icon = "fa-brands fa-instagram fa-lg" 
  [params.busuanzi_count]
    enable = true
    site_uv = true
    site_pv = true
    page_pv = true


# allow md file shows HTML format
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe= true
      hardWraps = false
      xhtml = false

# setup menu
sectionPagesMenu = "main"
[menu]
  [[menu.main]]
    name = "Home"
    # pre = '<i class="fa-solid fa-house"></i>'
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Store"
    # pre = '<i class="fa-solid fa-store"></i>'
    identifier = "store"
    url = "/stores/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    # pre = '<i class="fa-solid fa-newspaper"></i>'
    url = "/posts/"
    identifier = "posts"
    weight = 3
  [[menu.main]]
    name = "Abouts"
    # pre = '<i class="fa-solid fa-meteor"></i>'
    identifier = "about"
    url = "/about/"
    weight = 4


# code block buil-in tool
pygmentsUseClasses=true
pygmentsCodeFences=true